# Generated by Django 6.0.1 on 2026-02-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('INVESTOR', 'Investor'), ('MENTOR', 'Mentor')], default='INVESTOR', max_length=10),
        ),
    ]
