# Generated by Django 6.0.1 on 2026-02-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mentorlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='loss_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='mentor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='risk_level',
            field=models.CharField(choices=[('GREEN', 'Low Risk'), ('YELLOW', 'Medium Risk'), ('RED', 'High Risk')], default='GREEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.CharField(choices=[('EXECUTED', 'Executed'), ('PENDING_MENTOR', 'Pending Mentor'), ('LOCKED_BY_LOSS', 'Locked (Loss Limit)'), ('REJECTED', 'Rejected'), ('QUIZ_REQUIRED', 'Quiz Required')], default='EXECUTED', max_length=20),
        ),
    ]
