# Generated by Django 6.0.1 on 2026-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_traderequest_total_amount_user_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='brokerage_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
