# Generated by Django 6.0.1 on 2026-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_traderequest_brokerage_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discipline_score',
            field=models.IntegerField(default=50),
        ),
    ]
