# Generated by Django 6.0.1 on 2026-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_trading_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anxious_login_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LoginTracker',
        ),
    ]
