# Generated by Django 6.0.1 on 2026-03-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_logintracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginTracker',
        ),
    ]
