# Generated by Django 6.0.1 on 2026-03-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_logintracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anxious_login_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trading_locked_until',
        ),
    ]
