# Generated by Django 6.0.1 on 2026-03-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_user_anxious_login_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discipline_drop_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_trade_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trade_lock_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TradeUnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_reason', models.TextField(blank=True, default='')),
                ('mentor_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_unlock_reviews', to='api.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_unlock_requests', to='api.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
