# Generated by Django 6.0.1 on 2026-03-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_quiz_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='cooldown_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
