# Generated by Django 6.0.1 on 2026-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_quiz_cooldown_ends_at_alter_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='last_submitted_answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
